### ISSUE TITLE
DSB Item - Knowledge Management: Visual Productions (Q3)

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/future-plan#121]
Creation and management of key visual aids to support the DSB and CDR understanding of the different topics, releases and events.

- Creation of informative YouTube videos to support DSB roll out of the Data Standards
- Creation of YouTube videos to support consultation for the DSB
- Development of visual diagrams and enhanced images to support DSB Standards development

**Comment by CDR-API-Stream** [comment]
July 2023 Video Publications:

- [Video 65 Noting Paper 308 - narrated by Neale Morison (07/07/2023)](https://youtu.be/c-oap58o8Ls?si=kwpkyggyoJ8cdgxH)
- [Video 66 Decision Proposal 306 - narrated by Neale Morison (11/07/2023)](https://youtu.be/prMYxgkdqSI?si=8Wm5uObkR_BDNUMy)
- [Video 67 CDS 1.25.0 Release Walkthrough and Changes - with Neale Morison (21/07/2023)](https://youtu.be/yEgNVFVzDSI?si=PhXZ9LG_zKWdkr-1)
- [Video 68 Decision Proposal 314 - narrated by Neale Morison (28/07/2023)](https://youtu.be/1JGaUDhX5Jg?si=TH8FFXVMi1vT1Ib3)

**Comment by CDR-API-Stream** [comment]
August 2023 Video Publications:

- [Video 69 Decision Proposal 316 - narrated by Neale Morison (09/08/2023)](https://youtu.be/DqmWdra-NDE?si=H5XRUNlOY0CePGH0)
- [Video 70 Noting Paper 323 - narrated by Neale Morison (11/08/2023)](https://youtu.be/o59ovxkDAec?si=xB4Qvpprb9jSkavb)
- [Video 71 Decision Proposal 320 - narrated by Neale Morison (17/08/2023)](https://youtu.be/0js9dM1zlbI?si=_7xA1RQQdQo_5e3z)
- [Video 72 Product Comparator Demo - narrated by Neale Morison (31/08/2023)](https://youtu.be/twxLUuCA9NE?si=YVRw7qoCkkbjpwjr)

**Comment by CDR-Engagement-Stream** [comment]
September 2023 Video Publications:

- [Video 73 CDS 1.26.0 Release Walkthrough and Changes - with Jarryd Judd (04/09/2023)](https://youtu.be/9-VisdaVMkI?si=7iXOo5ux3nKlUC0u)
- [Video 74 Decision Proposal 317 - narrated by Neale Morison (07/09/2023)](https://youtu.be/IE9CutmCNYw?si=9ol4gA4baeMHyfW1)
- [Video 75 Design Paper 321 - narrated by Neale Morison (22/09/2023)](https://youtu.be/k4kgsPp_liA?si=iz4rNRupD0FfQBEB)
- [Video 76 Maintenance Iteration 16 - with Jarryd Judd (28/09/2023)](https://youtu.be/Ys8kmttW5Oc?si=-h_sgFp1P4tY3X3T)
