### ISSUE TITLE
DSB Item - CDR Implementation Call Q3 Facilitation

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/future-plan#122]
Facilitation of the weekly CDR Implementation calls including agenda management, minutes and follow up of actions and queries.

**Comment by CDR-API-Stream** [comment]
Agenda list of July 2023:
 * [27th of July 2023 Agenda](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/ACCC-&-DSB-%7C-CDR-Implementation-Call-Agenda-&-Meeting-Notes-%7C-27th-of-July-2023)
 * [20th of July 2023 Agenda](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/ACCC-&-DSB-%7C-CDR-Implementation-Call-Agenda-&-Meeting-Notes-%7C-20th-of-July-2023)
 * [13th of July 2023 Agenda](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/ACCC-&-DSB-%7C-CDR-Implementation-Call-Agenda-&-Meeting-Notes-%7C-13th-of-July-2023)
 * [6th of July 2023 Agenda](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/ACCC-&-DSB-%7C-CDR-Implementation-Call-Agenda-&-Meeting-Notes-%7C-6th-of-July-2023)

**Comment by CDR-API-Stream** [comment]
Agenda list of August 2023:
* [31st of August 2023 Agenda](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/ACCC-&-DSB-%7C-CDR-Implementation-Call-Agenda-&-Meeting-Notes-%7C-31st-of-August-2023)
* [24th of August 2023 Agenda](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/ACCC-&-DSB-%7C-CDR-Implementation-Call-Agenda-&-Meeting-Notes-%7C-24th-of-August-2023)
* [17th of August 2023 Agenda](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/ACCC-&-DSB-%7C-CDR-Implementation-Call-Agenda-&-Meeting-Notes-%7C-17th-of-August-2023)
* [10th of August 2023 Agenda](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/ACCC-&-DSB-%7C-CDR-Implementation-Call-Agenda-&-Meeting-Notes-%7C-10th-of-August-2023)
* [3rd of August 2023 Agenda](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/ACCC-&-DSB-%7C-CDR-Implementation-Call-Agenda-&-Meeting-Notes-%7C-3rd-of-August-2023)

**Comment by CDR-Engagement-Stream** [comment]
Agenda list of September 2023:

* [28th of September 2023](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/ACCC-&-DSB-%7C-CDR-Implementation-Call-Agenda-&-Meeting-Notes-%7C-28th-of-September-2023)
* [21st of September 2023](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/ACCC-&-DSB-%7C-CDR-Implementation-Call-Agenda-&-Meeting-Notes-%7C-21st-of-September-2023)
* [14th of September 2023](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/ACCC-&-DSB-%7C-CDR-Implementation-Call-Agenda-&-Meeting-Notes-%7C-14th-of-September-2023)
* [7th of September 2023](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/ACCC-&-DSB-%7C-CDR-Implementation-Call-Agenda-&-Meeting-Notes-%7C-7th-of-September-2023)
