### ISSUE TITLE
DSB Item - Knowledge Management: Visual Productions Q4

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/future-plan#134]
Creation and management of key visual aids to support the DSB and CDR understanding of the different topics, releases and events.

- Creation of informative YouTube videos to support DSB roll out of the Data Standards
- Creation of YouTube videos to support consultation for the DSB
- Development of visual diagrams and enhanced images to support DSB Standards development

**Comment by CDR-Engagement-Stream** [comment]
October publications:

- [Video 77 Decision Proposal 276 - narrated by Neale Morison (04/10/2023)](https://youtu.be/GimZ2N7IZLc?si=o4lLtSPJieJ6WCjS)
- [Video 78 CX Guidelines Site Update - narrated by Jarryd Judd (06/10/2023)](https://youtu.be/K905dntN1oE?si=khYMPC9bcvQwxUaS)
- [Video 79 Decision Proposal 327 - narrated by Jarryd Judd (12/10/2023) [obsolete]](https://youtu.be/O2HjZSMn6yI?si=GdV3868EuaB5BeXT)
- [Video 80 CDS 1.27.0 Release Walkthrough and Changes - with Jarryd Judd (17/10/2023) ](https://youtu.be/8CWiNelXkfc?si=-M9OL-4nG7nF8Jjw)
- [Video 81 Decision Proposal 327 - narrated by Jarryd Judd (17/10/2023)](https://youtu.be/rxonUZHbAI4?si=7ev1gUfFjR97gERW)
- [Video 82 Maintenance Iteration 17 Candidate Issues - narrated by Neale Morison (20/10/2023)](https://youtu.be/qlZLx_j2eFY?si=SYZBXoUqieQWUToi)
- [Video 83 Future Dated Obligations for Q4 of 2023 - narrated by Peter Nowotnik (25/10/2023)](https://youtu.be/Uytc4t4WUoI?si=RSn8XK2poVdIIXYj)
- [Video 84 Future Dated Obligations for Q1 of 2024 - narrated by Peter Nowotnik (27/10/2023)](https://youtu.be/9Y8p_2wCmzw?si=xDiK1UPDW_zfVgJ3)
- [Video 85 Decision Proposal 333 - narrated by Neale Morison (31/10/2023)](https://youtu.be/DExAPJgSZbs?si=kCV_zROFooLsiQAK)

**Comment by CDR-Engagement-Stream** [comment]
November publications:

- [Video 86 Decision Proposal 334 - narrated by Neale Morison (02/11/2023)](https://youtu.be/sIR4Pd7F_CY?si=wYIUoZML1FAnZNqD)
- [Video 87 Decision Proposal 318 - narrated by Neale Morison (03/11/2023)](https://youtu.be/JzjfDDb9ijc?si=B8iYaivhqjFiESTO)
- [Video 88 Introduction to the Consumer Data Standards - narrated by Neale Morison (10/11/2023)](https://youtu.be/v2kF6QuzySY?si=fafTyTtmK98wAlPR)
- [Video 89 Noting Paper 335 - narrated by Neale Morison (16/11/2023)](https://youtu.be/9GOJZRkxVWQ?si=rjVmI68lpNbO6K7S)
- [Video 90 CDS 1.28.0 Release Walkthrough and Changes - with Jarryd Judd (17/11/2023)](https://youtu.be/Qd9LcHSQRBE?si=aFnMpve-IQzP4Wsn)
- [Video 91 Decision Proposal 338 - narrated by Neale Morison (22/11/2023)](https://youtu.be/Kqs42_YiCdA?si=qkA0GYV3WLdKY-Lp)
- [Video 92 Non-Functional Requirements - narrated by Neale Morison (24/11/2023)](https://youtu.be/sLx-UCTgnLQ?si=EKxmaa_P1rLxnWwB)

**Comment by CDR-Engagement-Stream** [comment]
December publications:

- [Video 94 Get Metrics Guidance - narrated by Neale Morison (15/12/2023)](https://youtu.be/W0_HNeCQJGs?si=Q5KQZcpzVNPQLUUM)
- [Video 95 DSB Newsletter - narrated by Peter Nowotnik (19/12/2023)](https://youtu.be/F7SOPqDI-pk?si=LsxlvNO5-E2lvjkX)

**Comment by CDR-Engagement-Stream** [comment]
2023 Quarter 4 Complete.
