### ISSUE TITLE
DSB Item - CDR Implementation Call Facilitation Q4

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/future-plan#135]
Facilitation of the weekly CDR Implementation calls including agenda management, minutes and follow up of actions and queries.

**Comment by CDR-Engagement-Stream** [comment]
Agendas for CDR Implementation Call:
* [2023 December Agendas](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/ACCC-&-DSB-Data-Holder-Working-Group-Agenda-&-Notes-December-2023)
* [2023 November Agendas](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/ACCC-&-DSB-Data-Holder-Working-Group-Agenda-&-Notes-November-2023)
* [2023 October Agendas](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/ACCC-&-DSB-Data-Holder-Working-Group-Agenda-&-Notes-October-2023)
