### ISSUE TITLE
DSB Item - Initial consultation for Telco

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/future-plan#26]
# Problem Statement

This is a placeholder item to represent the demand arising from the designation of the next sector (after banking and energy).  No detail for this item yet exists.  It will be labelled as `sector: all` in the interim until more detail is known.

**Comment by JamesMBligh** [comment]
It is now understood that the next sector will be telecommunications.  Work will occur in Q1 2022 to perform initial consultation in preparation for standards development

**Comment by JamesMBligh** [comment]
Workshop and design paper have been published for initial consultation
