### ISSUE TITLE
DSB Item - Ongoing Energy standards consultation

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/future-plan#29]
# Problem Statement

Continuation of consulting on the technical and CX standards for the energy sector.  This item is likely to include the following:

- Multiple iterations of consultation on the whole technical standard defined in late 2020
- Energy sector workshops on the overall standards
- The development of standards for communication between the designated gateway and data holders
- Targeted consultations on authentication, authorisation and dashboards

**Comment by JamesMBligh** [comment]
Current consultation thread is open here:
https://github.com/ConsumerDataStandardsAustralia/standards/issues/149

This will be closed on the 12th with feedback incorporated into the draft and a new holistic thread will then be opened for further feedback.
