### ISSUE TITLE
DSB Item - First full draft of the technical standards for Energy

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/future-plan#3]
# Problem Statement

There is a need for a full draft of a set of technical standards that will meet the requirements of the Energy Designation and draft rules framework for the Energy sector.

This draft standard is not intended to be final or binding.  It is only expected to be complete and ready for a series of rounds for holistic consultation.

**Comment by JamesMBligh** [comment]
Energy standards have been published here:
https://consumerdatastandardsaustralia.github.io/standards/draft/energy-draft.html

Ongoing consultation on the draft is here:
https://github.com/ConsumerDataStandardsAustralia/standards/issues/149
