### ISSUE TITLE
DSB Item - Q2 Metrics Topics

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/future-plan#37]
# Problem Statement

Consultation on the following topics relating to metrics reporting:

* CX Metrics (held over from last quarter)
* Refusals and Error Handling
* Public Reporting and Dashboards

**Comment by JamesMBligh** [comment]
CX Metrics will be released in the next few days and has been extended to include authentication related metrics.

Other items are being developed.

**Comment by JamesMBligh** [comment]
Work is still outstanding on some of these items but this will now be managed under item #38
