### ISSUE TITLE
DSB Item - Support PKCE

### ISSUE THREAD

**Issue by adrcdr** [ConsumerDataStandardsAustralia/future-plan#40]
# Problem Statement

PKCE should be supported and FAPI require. It requested in [DP99](https://github.com/ConsumerDataStandardsAustralia/standards/issues/99) but never discuss.

**Comment by CDR-API-Stream** [comment]
This issue has been closed. The [intent](https://github.com/ConsumerDataStandardsAustralia/future-plan) of the DSB's Future Plan is to publish the high level work plan for the Data Standards Body. Once scheduled, items in this plan are broken down into multiple discrete [decision proposals](https://github.com/ConsumerDataStandardsAustralia/standards/issues) and consulted on with the CDR community.

The proper channel to raise community change requests is the [Standards Maintenance repository](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).
