### ISSUE TITLE
DSB Item - Test Harnesses for Retailer to AEMO interactions

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/future-plan#55]
# Problem Statement

Investigation of support tools for the new secondary responsibility interaction in the energy sector for Retailer to AEMO interaction

**Comment by JamesMBligh** [comment]
Planning and investigative work has been conducted.

Plan for Q1 is to develop:
- documented test cases
- a Postman collection for the AEMO exposed endpoints
- a mock set of APIs for AEMO exposed endpoints
