### ISSUE TITLE
DSB Item - Purpose specific consents

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/future-plan#7]
# Problem Statement

There is an opportunity that has been identified to simplify the consent process and technical implementations for specific use cases by creating purpose specific consents.

A purpose specific consent would bundle a group of permissions for a use case that is prevalent in the CDR community.  It may also involve the addition of a new, purpose specific end point to facilitate data minimisation. 

This item is currently being consulted on as part of [DP183](https://github.com/ConsumerDataStandardsAustralia/standards/issues/183)

**Comment by JamesMBligh** [comment]
This is now being worked on with the intent of creating an open consultation on the concept

**Comment by CDR-API-Stream** [comment]
Consultation on this topic has been raised under [Decision Proposal 183](https://github.com/ConsumerDataStandardsAustralia/standards/issues/183) and feedback will be received until Friday 23rd July 2021

**Comment by CDR-API-Stream** [comment]
Consultation has concluded. Feedback is currently being reviewed with a decision to the Chair pending.
