### ISSUE TITLE
DSB Item - Exploratory workshops for Action Initiation

### ISSUE THREAD

**Issue by markverstege** [ConsumerDataStandardsAustralia/future-plan#80]
# Problem Statement

The Treasury has [accepted](https://treasury.gov.au/publication/p2021-225462) many of the key recommendations in response to the [Inquiry into Future Directions for the Consumer Data Right - Final Report](https://treasury.gov.au/publication/inquiry-future-directions-consumer-data-right-final-report). Included in the accepted recommendations is expanding the CDR to action initiation. 

A series of early-stage exploratory workshops are planned to understand the existing processes for digital self-service of action initiation in currently designated sectors along with the earmarked future sectors. This consultation will seek to understand the current digital maturity that exists across organisations and commonality in processes. It will also seek to understand the key design considerations and building blocks to enable actions to be initiated within the CDR. This work will produce a high level reference architecture for action initiation.

**Main Contact:** Mark, Michael

**Comment by CDR-API-Stream** [comment]
Noting Paper 291 was published 30/01/2023: https://github.com/ConsumerDataStandardsAustralia/standards/issues/291.

The first workshop will be held on 7/03/2023 and it will focus on simple payments initiation.

**Comment by CDR-API-Stream** [comment]
This card is complete.  The initial investigative work for AI has been undertaken
