### ISSUE TITLE
DSB Item - Continuing Feedback on Draft Telco Standards 

### ISSUE THREAD

**Issue by CDR-CX-Stream** [ConsumerDataStandardsAustralia/future-plan#85]
Continuing feedback on draft telco standards.

- [DP302:]
(https://github.com/ConsumerDataStandardsAustralia/standards/issues/302): Telco Draft Feedback Cycle 2

**Main Contact:** Brian

**Comment by nils-work** [comment]
Closing this issue in line with the [comment here](https://github.com/ConsumerDataStandardsAustralia/standards/issues/302#issuecomment-1566363208).
