### ISSUE TITLE
DSB Item - Reassess Non Functional Requirements

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/future-plan#92]
Decision Proposal Required - reassess Non Functional Requirements to ensure ecosystem demands can be met and are commensurate with a Data Holders' customer base.

For more information refer to [Issue #534: Define concrete NFRs for unattended traffic during high traffic periods](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/534) and [Issue #541: Raising of Traffic Threshold NFRs specified in the CDS](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/541)

**Comment by nils-work** [comment]
[Decision Proposal 288 - Non-Functional Requirements Revision](https://github.com/ConsumerDataStandardsAustralia/standards/issues/288) has been published.

**Comment by CDR-API-Stream** [comment]
This ticket was addressed via Decision Proposal 288 on non-functional requirements and metrics API updates
